--------------------------------------------------------
--  Fichier créé - mercredi-février-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "P1506898"."PERSONNEL" 
   (	"IDENTIFIANT" NUMBER(5,0), 
	"NOM" VARCHAR2(50 BYTE), 
	"ROLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ASPE" ;
REM INSERTING into P1506898.PERSONNEL
SET DEFINE OFF;
Insert into P1506898.PERSONNEL (IDENTIFIANT,NOM,ROLE) values ('1','jean','jongleur');
Insert into P1506898.PERSONNEL (IDENTIFIANT,NOM,ROLE) values ('2','dupont','dompteur');
Insert into P1506898.PERSONNEL (IDENTIFIANT,NOM,ROLE) values ('3','jacques','directeur');
Insert into P1506898.PERSONNEL (IDENTIFIANT,NOM,ROLE) values ('4','toto','jongleur');
Insert into P1506898.PERSONNEL (IDENTIFIANT,NOM,ROLE) values ('5','jeremie','trapeziste');
Insert into P1506898.PERSONNEL (IDENTIFIANT,NOM,ROLE) values ('6','trump','CEO');
Insert into P1506898.PERSONNEL (IDENTIFIANT,NOM,ROLE) values ('7','martin','chauffeur de salle');
Insert into P1506898.PERSONNEL (IDENTIFIANT,NOM,ROLE) values ('8','kevin','lion');
Insert into P1506898.PERSONNEL (IDENTIFIANT,NOM,ROLE) values ('9','duplan','dresseur');
Insert into P1506898.PERSONNEL (IDENTIFIANT,NOM,ROLE) values ('10','jeanjean','guichetier');
--------------------------------------------------------
--  DDL for Index PK_PERSONNEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "P1506898"."PK_PERSONNEL" ON "P1506898"."PERSONNEL" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ASPE" ;
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "P1506898"."PERSONNEL" ADD CONSTRAINT "PK_PERSONNEL" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ASPE"  ENABLE;
